name: Build and deploy WAR to Azure Web App - trustworthy-product-reviews-group24

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '17'

      - name: Build WAR with Maven
        run: mvn -B -DskipTests clean package

      - name: Show build outputs (debug)
        run: dir target

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact           
          path: target/*.war           
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-artifact       

      - name: List downloaded files (debug)
        run: dir

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F6C13D330014183B9DE44DAB15E174F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C94CEB95511745B68A4B627BC1F28F2A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A06DB09B6DC445681B39311276A12FE }}

      - name: Deploy to Azure Web App (Tomcat)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trustworthy-product-reviews-group24'
          slot-name: 'Production'
          package: 'ROOT.war'        
