name: Build and deploy Python project to Azure Function App - trustworthy-product-reviews

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'
  FUNCTIONS_APP_PATH: .

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        working-directory: ${{ env.FUNCTIONS_APP_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C6A2DD04CE94B95B338B9E56EB5E5D0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ABF85597676D41648192EF2EAFF08D53 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DC5A3FCDBB7452BB41F6D5DF6119DF1 }}

      - name: Deploy to Azure Functions (Flex)
        uses: Azure/functions-action@v1
        with:
          app-name: 'trustworthy-product-reviews-ccbyfffshug4hpar' 
          slot-name: 'Production'
          package: ${{ env.FUNCTIONS_APP_PATH }}
          remote-build: true
